package CryptCompiler.Lexer.token;

public enum TokenType {
    INVALID,

    ID,

    COMMA, L_PAREN, R_PAREN, L_BOX, R_BOX, L_CURLY, R_CURLY, SEMICOLON, COLON, DB_COLON,
    TILDE, BLOCK_OP, DOT, Q_MARK, RIGHT_ARROW, LEFT_ARROW,

    GREATER_THAN, LESS_THAN, EQUALS, GREATER_OR_EQUAL, LESS_OR_EQUAL, NOT_EQUAL,

    INDENT, DEDENT, NEWLINE, WHITESPACE,

    PRINTLN, PRINT, ELSE, FOR, WHILE, SUPER, CLASS, SET, FN, NIL, AND, OR, NOT, TRUE, FALSE,
    RETURN, THIS,

    PLUS, MINUS, ASTERISK, SLASH, POWER, ROOT,

    STRING, NUMBER,

    EOF
    ;
}
